version: '3.1'

services:
  socat:
    image: bennythink/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: none

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password
    logging:
      driver: none

  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    depends_on:
      - socat
      - redis
    volumes:
      - ./data/vnstat/:/var/lib/vnstat/

  premium:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    volumes:
      - ./data/premium.session:/ytdlbot/ytdlbot/premium.session
    command: [ "/usr/local/bin/python",  "/ytdlbot/ytdlbot/premium.py" ]
